#!/bin/bash


file=gifs/$1

#PROTECT THE ORIGINAL GIF
filename=$(echo $file |cut -d"." -f1)
cp $file ${filename}_use.gif


#MUISTA LISAA UUDEN KUVAN NIMEN KAYTTO
file=${filename}_use.gif


#if test $(wmctrl -lG |grep $filename 2>&1 |wc -l) -eq 0;then gifview -a $file; fi

#GET SCREEN DIM

xscreendim=$(xdpyinfo |grep dimensions |awk '{print $2}'|cut -d'x' -f1)
yscreendim=$(xdpyinfo |grep dimensions |awk '{print $2}'|cut -d'x' -f2)


xwindim=$(echo $xscreendim / $2 |bc -l)
xwindim=$(printf "%.0f" $xwindim)
ywindim=$(echo $yscreendim / $3 |bc -l)
ywindim=$(printf "%.0f" $ywindim)


#xwindim=$(wmctrl -lG |grep $filename |awk '{print $5}')
#ywindim=$(wmctrl -lG |grep $filename |awk '{print $6}')

xpicdim=$(file $file |awk '{print $7}')
ypicdim=$(file $file |awk '{print $9}')

#echo $xwindim $ywindim $xpicdim $ypicdim 

# IMAGE TOO HIGH AND TOO NARROW 
#if [ $xpicdim -lt $xwindim ] && [ $ypicdim -ge $ywindim ]
if [ $xpicdim -lt $xwindim ] && [ $ypicdim -ge $ywindim ]
then
echo IMAGE TOO HIGH AND TOO NARROW 
	scale=$(echo $xwindim / $xpicdim |bc -l)
	ypicdimnew=$(echo $scale \* $ypicdim |bc -l)
	ypicdimnew=$(printf "%.0f" $ypicdimnew)
	xpicdimnew=$xwindim
	echo $xpicdimnew $ypicdimnew
fi

# IMAGE TOO WIDE AND TOO LOW
if [ $xpicdim -ge $xwindim ] && [ $ypicdim -lt $ywindim ]
then
#echo IMAGE TOO WIDE AND TOO LOW
	scale=$(echo $ywindim / $ypicdim |bc -l)
	xpicdimnew=$(echo $scale \* $xpicdim |bc -l)
	xpicdimnew=$(printf "%.0f" $xpicdimnew)
	ypicdimnew=$ywindim
	echo $xpicdimnew $ypicdimnew
fi

# IMAGE TOO HIGH AND TOO WIDE
if [ $xpicdim -ge $xwindim ] && [ $ypicdim -ge $ywindim ]
then
#echo IMAGE TOO HIGH AND TOO WIDE
	xdif=$(echo $xpicdim - $xwindim |bc -l)
	ydif=$(echo $ypicdim - $ywindim |bc -l)


	if [ $xdif -lt $ydif ]
	then
		scale=$(echo $xwindim / $xpicdim |bc -l)
		xpicdimnew=$(echo $xpicdim \* $scale |bc -l)
		xpicdimnew=$(printf "%.0f" $xpicdimnew)
		ypicdimnew=$(echo $ypicdim \* $scale |bc -l) 
		ypicdimnew=$(printf "%.0f" $ypicdimnew)
	fi

	if [ $xdif -gt $ydif ]
	then
		
		scale=$(echo $ywindim / $ypicdim |bc -l)
		xpicdimnew=$(echo $xpicdim \* $scale |bc -l)
		xpicdimnew=$(printf "%.0f" $xpicdimnew)
		ypicdimnew=$(echo $ypicdim \* $scale |bc -l)
		ypicdimnew=$(printf "%.0f" $ypicdimnew)
		
	fi
fi


# IMAGE TOO LOW AND NARROW
if [ $xpicdim -le $xwindim ] && [ $ypicdim -le $ywindim ]
then
echo IMAGE TOO LOW AND NARROW
	xdif=$(echo $xwindim - $xpicdim |bc -l)
	ydif=$(echo $ywindim - $ypicdim |bc -l)

	if [ $xdif -lt $ydif ]
	then
		scale=$(echo $xwindim / $xpicdim |bc -l)
		xpicdimnew=$(echo $xpicdim \* $scale |bc -l)
		xpicdimnew=$(printf "%.0f" $xpicdimnew)
		ypicdimnew=$(echo $ypicdim \* $scale |bc -l) 
		ypicdimnew=$(printf "%.0f" $ypicdimnew)
	fi

	if [ $xdif -gt $ydif ]
	then
		
		scale=$(echo $ywindim / $ypicdim |bc -l)
		xpicdimnew=$(echo $xpicdim \* $scale |bc -l)
		xpicdimnew=$(printf "%.0f" $xpicdimnew)
		ypicdimnew=$(echo $ypicdim \* $scale |bc -l)
		ypicdimnew=$(printf "%.0f" $ypicdimnew)
		
	fi
fi

newsize=$(echo ${xpicdimnew}x${ypicdimnew})
gifsicle $file --resize $newsize > ${filename}_res.gif
gifview -a ${filename}_res.gif 

rm ${filename}_res.gif
rm ${filename}_use.gif

